SCIP-SDP: disp_sdpiterations.c File Reference
disp_sdpiterations.c File Reference
Column to display the total number of SDP iterations.
Macros
#define DISP_NAME "sdpiterations"
#define DISP_DESC "number of SDP iterations"
#define DISP_HEADER "SDP iter"
#define DISP_WIDTH 8
#define DISP_PRIORITY 30001
#define DISP_POSITION 1000
#define DISP_STRIPLINE TRUE
Functions
static SCIP_DECL_DISPCOPY (dispCopySdpiterations)
static SCIP_DECL_DISPFREE (dispFreeSdpiterations)
static SCIP_DECL_DISPINITSOL (dispInitsolSdpiterations)
static SCIP_DECL_DISPOUTPUT (dispOutputSdpiterations)
SCIP_RETCODE SCIPincludeDispSdpiterations (SCIP *scip)
Detailed Description
Column to display the total number of SDP iterations.
Author
Tristan Gally
Definition in file disp_sdpiterations.c.
Macro Definition Documentation
#define DISP_NAME "sdpiterations"
Definition at line 46 of file disp_sdpiterations.c.
Referenced by SCIPincludeDispSdpiterations().
#define DISP_DESC "number of SDP iterations"
Definition at line 47 of file disp_sdpiterations.c.
Referenced by SCIPincludeDispSdpiterations().
#define DISP_HEADER "SDP iter"
Definition at line 48 of file disp_sdpiterations.c.
Referenced by SCIPincludeDispSdpiterations().
#define DISP_WIDTH 8
the width of the display column
Definition at line 49 of file disp_sdpiterations.c.
Referenced by SCIP_DECL_DISPOUTPUT(), and SCIPincludeDispSdpiterations().
#define DISP_PRIORITY 30001
the priority of the display column
Definition at line 50 of file disp_sdpiterations.c.
Referenced by SCIPincludeDispSdpiterations().
#define DISP_POSITION 1000
the relative position of the display column
Definition at line 51 of file disp_sdpiterations.c.
Referenced by SCIPincludeDispSdpiterations().
#define DISP_STRIPLINE TRUE
default for displaying column separated with a line from its right neighbor
Definition at line 52 of file disp_sdpiterations.c.
Referenced by SCIPincludeDispSdpiterations().
Function Documentation
static SCIP_DECL_DISPCOPY (dispCopySdpiterations) static
copy method for dialog plugins (called when SCIP copies plugins)
Definition at line 75 of file disp_sdpiterations.c.
References SCIPincludeDispSdpiterations().
static SCIP_DECL_DISPFREE (dispFreeSdpiterations) static
destructor of display column to free user data (called when SCIP is exiting)
Definition at line 88 of file disp_sdpiterations.c.
static SCIP_DECL_DISPINITSOL (dispInitsolSdpiterations) static
solving process initialization method of display column (called when branch and bound process is about to begin)
Definition at line 105 of file disp_sdpiterations.c.
static SCIP_DECL_DISPOUTPUT (dispOutputSdpiterations) static
output method of display column to output file stream 'file'
Definition at line 121 of file disp_sdpiterations.c.
References DISP_WIDTH, and SCIPrelaxSdpGetNIterations().
SCIP_RETCODE SCIPincludeDispSdpiterations (SCIP * scip)
creates the SDP-iterations display column and includes it in SCIP
Parameters
scip SCIP data structure
Definition at line 144 of file disp_sdpiterations.c.
References DISP_DESC, DISP_HEADER, DISP_NAME, DISP_POSITION, DISP_PRIORITY, DISP_STRIPLINE, and DISP_WIDTH.
Referenced by runSCIP(), and SCIP_DECL_DISPCOPY().