SCIP-SDP: disp_sdpavgiterations.c File Reference
disp_sdpavgiterations.c File Reference
Column to display the average number of SDP iterations.
Macros
#define DISP_NAME "sdpavgiterations"
#define DISP_DESC "average number of SDP iterations"
#define DISP_HEADER "SDP it/n"
#define DISP_WIDTH 8
#define DISP_PRIORITY 25001
#define DISP_POSITION 1400
#define DISP_STRIPLINE TRUE
Functions
static SCIP_DECL_DISPCOPY (dispCopySdpavgiterations)
static SCIP_DECL_DISPFREE (dispFreeSdpavgiterations)
static SCIP_DECL_DISPINITSOL (dispInitsolSdpavgiterations)
static SCIP_DECL_DISPOUTPUT (dispOutputSdpavgiterations)
SCIP_RETCODE SCIPincludeDispSdpavgiterations (SCIP *scip)
Detailed Description
Column to display the average number of SDP iterations.
Author
Tristan Gally
Definition in file disp_sdpavgiterations.c.
Macro Definition Documentation
#define DISP_NAME "sdpavgiterations"
Definition at line 46 of file disp_sdpavgiterations.c.
Referenced by SCIPincludeDispSdpavgiterations().
#define DISP_DESC "average number of SDP iterations"
Definition at line 47 of file disp_sdpavgiterations.c.
Referenced by SCIPincludeDispSdpavgiterations().
#define DISP_HEADER "SDP it/n"
Definition at line 48 of file disp_sdpavgiterations.c.
Referenced by SCIPincludeDispSdpavgiterations().
#define DISP_WIDTH 8
the width of the display column
Definition at line 49 of file disp_sdpavgiterations.c.
Referenced by SCIPincludeDispSdpavgiterations().
#define DISP_PRIORITY 25001
the priority of the display column
Definition at line 50 of file disp_sdpavgiterations.c.
Referenced by SCIPincludeDispSdpavgiterations().
#define DISP_POSITION 1400
the relative position of the display column
Definition at line 51 of file disp_sdpavgiterations.c.
Referenced by SCIPincludeDispSdpavgiterations().
#define DISP_STRIPLINE TRUE
default for displaying column separated with a line from its right neighbor
Definition at line 52 of file disp_sdpavgiterations.c.
Referenced by SCIPincludeDispSdpavgiterations().
Function Documentation
static SCIP_DECL_DISPCOPY (dispCopySdpavgiterations) static
copy method for dialog plugins (called when SCIP copies plugins)
Definition at line 74 of file disp_sdpavgiterations.c.
References SCIPincludeDispSdpavgiterations().
static SCIP_DECL_DISPFREE (dispFreeSdpavgiterations) static
destructor of display column to free user data (called when SCIP is exiting)
Definition at line 87 of file disp_sdpavgiterations.c.
static SCIP_DECL_DISPINITSOL (dispInitsolSdpavgiterations) static
solving process initialization method of display column (called when branch and bound process is about to begin)
Definition at line 104 of file disp_sdpavgiterations.c.
static SCIP_DECL_DISPOUTPUT (dispOutputSdpavgiterations) static
output method of display column to output file stream 'file'
Definition at line 121 of file disp_sdpavgiterations.c.
References SCIPrelaxSdpGetNIterations(), and SCIPrelaxSdpGetNSdpCalls().
SCIP_RETCODE SCIPincludeDispSdpavgiterations (SCIP * scip)
creates the SDP-average-iterations display column and includes it in SCIP
Parameters
scip SCIP data structure
Definition at line 147 of file disp_sdpavgiterations.c.
References DISP_DESC, DISP_HEADER, DISP_NAME, DISP_POSITION, DISP_PRIORITY, DISP_STRIPLINE, and DISP_WIDTH.
Referenced by runSCIP(), and SCIP_DECL_DISPCOPY().