SCIP-SDP: scip Namespace Reference
scip Namespace Reference
Classes
struct LProw
class SDPBlock
class LPBlock
class ObjReaderSDPA
Functions
static SCIP_RETCODE dropComments (std::istream *file)
static SCIP_RETCODE dropSpaceNewlineError (std::istream &line)
static SCIP_RETCODE checkForLineEnd (std::istream &line)
static SCIP_RETCODE testDigit (std::istream *file)
static SCIP_RETCODE checkIndex (const char *indexname, int value, int ub)
Function Documentation
static SCIP_RETCODE scip::dropComments (std::istream * file) static
function for removing comments in between the variable & block definitions
Definition at line 87 of file objreader_sdpa.cpp.
Referenced by scip::ObjReaderSDPA::scip_read().
static SCIP_RETCODE scip::dropSpaceNewlineError (std::istream & line) static
Definition at line 103 of file objreader_sdpa.cpp.
Referenced by scip::ObjReaderSDPA::scip_read().
static SCIP_RETCODE scip::checkForLineEnd (std::istream & line) static
Definition at line 124 of file objreader_sdpa.cpp.
Referenced by scip::ObjReaderSDPA::scip_read().
static SCIP_RETCODE scip::testDigit (std::istream * file) static
function to test whether the next character in the input string is a digit (or a minus), if it isn't SCIP aborts with a corresponding error
Definition at line 150 of file objreader_sdpa.cpp.
Referenced by scip::ObjReaderSDPA::scip_read().
static SCIP_RETCODE scip::checkIndex (const char * indexname, int value, int ub) static
function to check whether the given index is within the given bounds, if not an error message for the given string will be thrown
Definition at line 165 of file objreader_sdpa.cpp.
Referenced by scip::ObjReaderSDPA::scip_read().