SCIP-SDP: relax_sdp.h File Reference
relax_sdp.h File Reference
SDP relaxator.
Functions
EXTERN SCIP_RETCODE SCIPincludeRelaxSdp (SCIP *scip)
EXTERN SCIP_RETCODE SCIPrelaxSdpGetPrimalBoundVars (SCIP_RELAX *relax, SCIP_Real *lbvars, SCIP_Real *ubvars, int *arraylength)
EXTERN SCIP_RETCODE SCIPrelaxSdpRelaxVal (SCIP_RELAX *relax, SCIP_Bool *success, SCIP_Real *objval)
EXTERN SCIP_RETCODE SCIPrelaxSdpGetRelaxSol (SCIP *scip, SCIP_RELAX *relax, SCIP_Bool *success, SCIP_Real *solarray, int *sollength)
EXTERN long int SCIPrelaxSdpGetSdpNode (SCIP_RELAX *relax)
EXTERN SCIP_Bool SCIPrelaxSdpSolvedOrig (SCIP_RELAX *relax)
EXTERN int SCIPrelaxSdpGetNIterations (SCIP_RELAX *relax)
EXTERN int SCIPrelaxSdpGetNSdpCalls (SCIP_RELAX *relax)
Detailed Description
SDP relaxator.
Author
Sonja Mars
Tristan Gally
Definition in file relax_sdp.h.
Function Documentation
EXTERN SCIP_RETCODE SCIPincludeRelaxSdp (SCIP * scip)
creates the SDP relaxator and includes it in SCIP
Parameters
scip SCIP data structure
Definition at line 964 of file relax_sdp.c.
References DEFAULT_OBJLIMIT, DEFAULT_SDPSOLVEREPSILON, DEFAULT_SDPSOLVERFEASTOL, RELAX_DESC, RELAX_FREQ, RELAX_NAME, RELAX_PRIORITY, SCIPsdpiCreate(), SCIPsdpiGetSolverDesc(), and SCIPsdpiGetSolverName().
Referenced by runSCIP(), and SCIP_DECL_RELAXCOPY().
EXTERN SCIP_RETCODE SCIPrelaxSdpGetPrimalBoundVars (SCIP_RELAX * relax, SCIP_Real * lbvars, SCIP_Real * ubvars, int * arraylength)
gets the primal variables corresponding to the lower and upper variable-bounds in the dual problem
The last input should specify the length of the arrays. If this is less than the number of variables, the needed length will be returned and a debug message thrown.
Note
if a variable is either fixed or unbounded in the dual problem, a zero will be returned for the non-existent primal variable.
Parameters
relax SDP relaxator to information for
lbvars pointer to store the values of the variables corresponding to lower bounds in the dual problems
ubvars pointer to store the values of the variables corresponding to upper bounds in the dual problems
arraylength input: length of lbvars and ubvars
output: number of elements inserted into lbvars/ubvars (or needed length if it wasn't sufficient)
Definition at line 1025 of file relax_sdp.c.
References SCIPsdpiGetPrimalBoundVars().
Referenced by SCIP_DECL_PROPEXEC().
EXTERN SCIP_RETCODE SCIPrelaxSdpRelaxVal (SCIP_RELAX * relax, SCIP_Bool * success, SCIP_Real * objval)
returns optimal objective value of the current SDP relaxation, if the last SDP relaxation was successfully solved
Parameters
relax SDP relaxator to get objective value for
success pointer to store whether the last SDP relaxation solved successfully
objval pointer to store the optimal objective value of the SDP relaxation
Definition at line 1050 of file relax_sdp.c.
Referenced by SCIP_DECL_PROPEXEC().
EXTERN SCIP_RETCODE SCIPrelaxSdpGetRelaxSol (SCIP * scip, SCIP_RELAX * relax, SCIP_Bool * success, SCIP_Real * solarray, int * sollength)
returns values of all variables in the solution of the current SDP relaxation, if the last SDP relaxation was successfully solved
Parameters
scip SCIP pointer
relax SDP relaxator to get solution for
success pointer to store whether the last SDP relaxation solved successfully
solarray pointer to store the solution, this has to be at least length nvars
sollength length of the solarray
Definition at line 1072 of file relax_sdp.c.
References SCIPsdpiGetSol().
EXTERN long int SCIPrelaxSdpGetSdpNode (SCIP_RELAX * relax)
get the number of the SCIP-node to which the current SDP solution belongs
Parameters
relax SDP relaxator to get solution for
Definition at line 1103 of file relax_sdp.c.
Referenced by SCIP_DECL_PROPEXEC().
EXTERN SCIP_Bool SCIPrelaxSdpSolvedOrig (SCIP_RELAX * relax)
was the original problem solved for the last SDP-Node (or a penalty formulation) ?
Parameters
relax SDP relaxator to get solution for
Definition at line 1114 of file relax_sdp.c.
References SCIPsdpiSolvedOrig().
Referenced by SCIP_DECL_PROPEXEC().
EXTERN int SCIPrelaxSdpGetNIterations (SCIP_RELAX * relax)
returns total number of SDP iterations
Parameters
relax SDP relaxator to get the iterations for
Definition at line 1131 of file relax_sdp.c.
Referenced by SCIP_DECL_DISPOUTPUT().
EXTERN int SCIPrelaxSdpGetNSdpCalls (SCIP_RELAX * relax)
returns number of solved SDP relaxations
Parameters
relax SDP relaxator to get the number of calls for
Definition at line 1142 of file relax_sdp.c.
Referenced by SCIP_DECL_DISPOUTPUT().