################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src \
obj/O.linux.x86_64.gnu.opt \
obj/O.linux.x86_64.gnu.dbg \
lib/scip/tests/src/test \
lib/scip/tests/src/symmetry \
lib/scip/tests/src/sepa \
lib/scip/tests/src/scip \
lib/scip/tests/src/relax \
lib/scip/tests/src/reader \
lib/scip/tests/src/prop \
lib/scip/tests/src/presol \
lib/scip/tests/src/nlpi \
lib/scip/tests/src/misc \
lib/scip/tests/src/lpi \
lib/scip/tests/src/heur \
lib/scip/tests/src/cons/superindicator \
lib/scip/tests/src/cons/quadratic \
lib/scip/tests/src/cons/nonlinear \
lib/scip/tests/src/cons/linear \
lib/scip/tests/src/cons/knapsack \
lib/scip/tests/src/cons \
lib/scip/tests/src/bugs \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/test \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/sepa \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/scip \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/relax \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/reader \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/prop \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/presol \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/nlpi \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/misc \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/lpi \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/heur \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/cons/superindicator \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/cons/quadratic \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/cons/nonlinear \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/cons/linear \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/cons/knapsack \
lib/scip/tests/obj/shared/O.linux.x86_64.gnu.dbg/cons \
lib/scip/tests/include \
lib/scip/tests/Criterion/test \
lib/scip/tests/Criterion/src/string \
lib/scip/tests/Criterion/src/log \
lib/scip/tests/Criterion/src/io \
lib/scip/tests/Criterion/src/entry \
lib/scip/tests/Criterion/src/core \
lib/scip/tests/Criterion/src/compat \
lib/scip/tests/Criterion/samples \
lib/scip/tests/Criterion/samples/tests \
lib/scip/tests/Criterion/dependencies/wingetopt/src \
lib/scip/tests/Criterion/dependencies/libcsptr/src \
lib/scip/tests/Criterion/dependencies/libcsptr/check/test \
lib/scip/tests/Criterion/dependencies/klib/test \
lib/scip/tests/Criterion/dependencies/klib \
lib/scip/tests/Criterion/dependencies/dyncall/test/thunk \
lib/scip/tests/Criterion/dependencies/dyncall/test/syscall \
lib/scip/tests/Criterion/dependencies/dyncall/test/suite \
lib/scip/tests/Criterion/dependencies/dyncall/test/sign \
lib/scip/tests/Criterion/dependencies/dyncall/test/sharedlib \
lib/scip/tests/Criterion/dependencies/dyncall/test/samples/composite \
lib/scip/tests/Criterion/dependencies/dyncall/test/samples/calls \
lib/scip/tests/Criterion/dependencies/dyncall/test/resolve_self \
lib/scip/tests/Criterion/dependencies/dyncall/test/plain \
lib/scip/tests/Criterion/dependencies/dyncall/test/nm \
lib/scip/tests/Criterion/dependencies/dyncall/test/malloc_wx \
lib/scip/tests/Criterion/dependencies/dyncall/test/hacking-mips \
lib/scip/tests/Criterion/dependencies/dyncall/test/hacking-arm-thumb-interwork \
lib/scip/tests/Criterion/dependencies/dyncall/test/hacking-arm-thumb-interwork/diff-gcc-defs \
lib/scip/tests/Criterion/dependencies/dyncall/test/gen-masm \
lib/scip/tests/Criterion/dependencies/dyncall/test/common \
lib/scip/tests/Criterion/dependencies/dyncall/test/callf \
lib/scip/tests/Criterion/dependencies/dyncall/test/callback_suite \
lib/scip/tests/Criterion/dependencies/dyncall/test/callback_plain \
lib/scip/tests/Criterion/dependencies/dyncall/test/call_suite \
lib/scip/tests/Criterion/dependencies/dyncall/portasm \
lib/scip/tests/Criterion/dependencies/dyncall/dynload \
lib/scip/tests/Criterion/dependencies/dyncall/dyncallback \
lib/scip/tests/Criterion/dependencies/dyncall/dyncall \
lib/scip/tests/Criterion/build/dependencies/libcsptr/CMakeFiles/csptr.dir/src \
lib/scip/tests/Criterion/build/dependencies/dyncall/dyncall/CMakeFiles/dyncall_s.dir \
lib/scip/tests/Criterion/build/CMakeFiles/criterion.dir/src/string \
lib/scip/tests/Criterion/build/CMakeFiles/criterion.dir/src/log \
lib/scip/tests/Criterion/build/CMakeFiles/criterion.dir/src/io \
lib/scip/tests/Criterion/build/CMakeFiles/criterion.dir/src/entry \
lib/scip/tests/Criterion/build/CMakeFiles/criterion.dir/src/core \
lib/scip/tests/Criterion/build/CMakeFiles/criterion.dir/src/compat \
lib/scip/tests/Criterion/build/CMakeFiles/2.8.12.2/CompilerIdC \
lib/scip/src/xml \
lib/scip/src/tpi \
lib/scip/src/tinycthread \
lib/scip/src/tclique \
lib/scip/src/scip \
lib/scip/src/nlpi \
lib/scip/src \
lib/scip/src/lpi \
lib/scip/src/dijkstra \
lib/scip/src/blockmemshell \
lib/scip/scripts/randomsetting/src \
lib/scip/opt-msk/tests/CMakeFiles/unittest-nlpi-nlpi.dir/src/nlpi \
lib/scip/opt-msk/tests/CMakeFiles/unittest-lpi-solve.dir/src/lpi \
lib/scip/opt-msk/tests/CMakeFiles/unittest-lpi-matrix.dir/src/lpi \
lib/scip/opt-msk/tests/CMakeFiles/unittest-lpi-boundchg.dir/src/lpi \
lib/scip/opt-msk/tests/CMakeFiles/unittest-lpi-bases.dir/src/lpi \
lib/scip/opt-msk/src/CMakeFiles/scip.dir/xml \
lib/scip/opt-msk/src/CMakeFiles/scip.dir/tpi \
lib/scip/opt-msk/src/CMakeFiles/scip.dir/tclique \
lib/scip/opt-msk/src/CMakeFiles/scip.dir/scip \
lib/scip/opt-msk/src/CMakeFiles/scip.dir/objscip \
lib/scip/opt-msk/src/CMakeFiles/scip.dir/nlpi \
lib/scip/opt-msk/src/CMakeFiles/scip.dir \
lib/scip/opt-msk/src/CMakeFiles/scip.dir/lpi \
lib/scip/opt-msk/src/CMakeFiles/scip.dir/dijkstra \
lib/scip/opt-msk/src/CMakeFiles/scip.dir/blockmemshell \
lib/scip/opt-msk/src/CMakeFiles/libscip.dir/xml \
lib/scip/opt-msk/src/CMakeFiles/libscip.dir/tpi \
lib/scip/opt-msk/src/CMakeFiles/libscip.dir/tclique \
lib/scip/opt-msk/src/CMakeFiles/libscip.dir/scip \
lib/scip/opt-msk/src/CMakeFiles/libscip.dir/objscip \
lib/scip/opt-msk/src/CMakeFiles/libscip.dir/nlpi \
lib/scip/opt-msk/src/CMakeFiles/libscip.dir/lpi \
lib/scip/opt-msk/src/CMakeFiles/libscip.dir/dijkstra \
lib/scip/opt-msk/src/CMakeFiles/libscip.dir/blockmemshell \
lib/scip/opt-msk/examples/TSP/CMakeFiles/sciptsp.dir/src \
lib/scip/opt-msk/examples/Relaxator/CMakeFiles/relaxator.dir/src \
lib/scip/opt-msk/examples/Queens/CMakeFiles/queens.dir/src \
lib/scip/opt-msk/examples/LOP/CMakeFiles/lop.dir/src \
lib/scip/opt-msk/examples/GMI/CMakeFiles/gmi.dir/src \
lib/scip/opt-msk/examples/Eventhdlr/CMakeFiles/eventhdlr.dir/src \
lib/scip/opt-msk/examples/CallableLibrary/CMakeFiles/string.dir/src \
lib/scip/opt-msk/examples/CallableLibrary/CMakeFiles/gastrans.dir/src \
lib/scip/opt-msk/examples/CallableLibrary/CMakeFiles/circle.dir/src \
lib/scip/opt-msk/examples/Binpacking/CMakeFiles/binpacking.dir/src \
lib/scip/opt-msk/CMakeFiles \
lib/scip/opt-msk/CMakeFiles/3.9.1/CompilerIdC \
lib/scip/opt/tests/CMakeFiles/unittest-scip-probingobj.dir/src/scip \
lib/scip/opt/tests/CMakeFiles/unittest-nlpi-nlpi.dir/src/nlpi \
lib/scip/opt/tests/CMakeFiles/unittest-misc-rbtreetest.dir/src/misc \
lib/scip/opt/tests/CMakeFiles/unittest-misc-dbldblarith.dir/src/misc \
lib/scip/opt/src/CMakeFiles/scip.dir/xml \
lib/scip/opt/src/CMakeFiles/scip.dir/tpi \
lib/scip/opt/src/CMakeFiles/scip.dir/tclique \
lib/scip/opt/src/CMakeFiles/scip.dir/scip \
lib/scip/opt/src/CMakeFiles/scip.dir/objscip \
lib/scip/opt/src/CMakeFiles/scip.dir/nlpi \
lib/scip/opt/src/CMakeFiles/scip.dir \
lib/scip/opt/src/CMakeFiles/scip.dir/lpi \
lib/scip/opt/src/CMakeFiles/scip.dir/dijkstra \
lib/scip/opt/src/CMakeFiles/scip.dir/blockmemshell \
lib/scip/opt/src/CMakeFiles/libscip.dir/xml \
lib/scip/opt/src/CMakeFiles/libscip.dir/tpi \
lib/scip/opt/src/CMakeFiles/libscip.dir/tclique \
lib/scip/opt/src/CMakeFiles/libscip.dir/scip \
lib/scip/opt/src/CMakeFiles/libscip.dir/objscip \
lib/scip/opt/src/CMakeFiles/libscip.dir/nlpi \
lib/scip/opt/src/CMakeFiles/libscip.dir/lpi \
lib/scip/opt/src/CMakeFiles/libscip.dir/dijkstra \
lib/scip/opt/src/CMakeFiles/libscip.dir/blockmemshell \
lib/scip/opt/CMakeFiles \
lib/scip/opt/CMakeFiles/3.9.1/CompilerIdC \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/lib/xml \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/lib/tpi \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/lib/tclique \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/lib/symmetry \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/lib/scip \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/lib/objscip \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/lib/nlpi \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/lib/lpi \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/lib/dijkstra \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/lib/blockmemshell \
lib/scip/obj/static/O.linux.x86_64.gnu.opt/bin \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/lib/xml \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/lib/tpi \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/lib/tclique \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/lib/symmetry \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/lib/scip \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/lib/objscip \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/lib/nlpi \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/lib/lpi \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/lib/dijkstra \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/lib/blockmemshell \
lib/scip/obj/static/O.linux.x86_64.gnu.dbg/bin \
lib/scip/obj/shared/O.linux.x86_64.gnu.opt/lib/xml \
lib/scip/obj/shared/O.linux.x86_64.gnu.opt/lib/tpi \
lib/scip/obj/shared/O.linux.x86_64.gnu.opt/lib/tclique \
lib/scip/obj/shared/O.linux.x86_64.gnu.opt/lib/scip \
lib/scip/obj/shared/O.linux.x86_64.gnu.opt/lib/objscip \
lib/scip/obj/shared/O.linux.x86_64.gnu.opt/lib/nlpi \
lib/scip/obj/shared/O.linux.x86_64.gnu.opt/lib/lpi \
lib/scip/obj/shared/O.linux.x86_64.gnu.opt/lib/dijkstra \
lib/scip/obj/shared/O.linux.x86_64.gnu.opt/lib/blockmemshell \
lib/scip/obj/shared/O.linux.x86_64.gnu.opt/bin \
lib/scip/obj/shared/O.linux.x86_64.gnu.dbg/lib/xml \
lib/scip/obj/shared/O.linux.x86_64.gnu.dbg/lib/tpi \
lib/scip/obj/shared/O.linux.x86_64.gnu.dbg/lib/tclique \
lib/scip/obj/shared/O.linux.x86_64.gnu.dbg/lib/scip \
lib/scip/obj/shared/O.linux.x86_64.gnu.dbg/lib/objscip \
lib/scip/obj/shared/O.linux.x86_64.gnu.dbg/lib/nlpi \
lib/scip/obj/shared/O.linux.x86_64.gnu.dbg/lib/lpi \
lib/scip/obj/shared/O.linux.x86_64.gnu.dbg/lib/dijkstra \
lib/scip/obj/shared/O.linux.x86_64.gnu.dbg/lib/blockmemshell \
lib/scip/obj/shared/O.linux.x86_64.gnu.dbg/bin \
lib/scip/obj/O.linux.x86_64.gnu.opt/lib/xml \
lib/scip/obj/O.linux.x86_64.gnu.opt/lib/tclique \
lib/scip/obj/O.linux.x86_64.gnu.opt/lib/scip \
lib/scip/obj/O.linux.x86_64.gnu.opt/lib/objscip \
lib/scip/obj/O.linux.x86_64.gnu.opt/lib/nlpi \
lib/scip/obj/O.linux.x86_64.gnu.opt/lib/lpi \
lib/scip/obj/O.linux.x86_64.gnu.opt/lib/dijkstra \
lib/scip/obj/O.linux.x86_64.gnu.opt/lib/blockmemshell \
lib/scip/obj/O.linux.x86_64.gnu.opt/bin \
lib/scip/obj/O.linux.x86_64.gnu.dbg/lib/xml \
lib/scip/obj/O.linux.x86_64.gnu.dbg/lib/tclique \
lib/scip/obj/O.linux.x86_64.gnu.dbg/lib/scip \
lib/scip/obj/O.linux.x86_64.gnu.dbg/lib/objscip \
lib/scip/obj/O.linux.x86_64.gnu.dbg/lib/nlpi \
lib/scip/obj/O.linux.x86_64.gnu.dbg/lib/lpi \
lib/scip/obj/O.linux.x86_64.gnu.dbg/lib/dijkstra \
lib/scip/obj/O.linux.x86_64.gnu.dbg/lib/blockmemshell \
lib/scip/obj/O.linux.x86_64.gnu.dbg/bin \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/src \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/libseq \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/examples \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/SCILAB \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/PORD/lib \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/MATLAB \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Metis \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Metis/metis-4.0/Test \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Metis/metis-4.0/Programs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Metis/metis-4.0/Lib \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/ThirdParty/Metis/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/tutorial/CodingExercise/C/3-solution \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/tutorial/CodingExercise/C/2-mistake \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/tutorial/CodingExercise/C/1-skeleton \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/test \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/contrib/LinearSolverLoader \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/contrib/LinearSolverLoader/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/contrib/CGPenalty \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/contrib/CGPenalty/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/LinAlg/TMatrices \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/LinAlg/TMatrices/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/LinAlg \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/LinAlg/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Interfaces \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Interfaces/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Common \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Common/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Apps/CUTErInterface \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Apps/CUTErInterface/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Algorithm/LinearSolvers \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Algorithm/LinearSolvers/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Algorithm \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Algorithm/.libs \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/examples/hs071_c \
lib/scip/lib/static/ipopt.linux.x86_64.gnu.opt/Ipopt/MSVisualStudio/v8-ifort/IpOptFSS \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/src \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/libseq \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/examples \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/SCILAB \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/PORD/lib \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/MUMPS/MATLAB \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Mumps/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Metis \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Metis/metis-4.0/Test \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Metis/metis-4.0/Programs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Metis/metis-4.0/Lib \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/ThirdParty/Metis/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/tutorial/CodingExercise/C/3-solution \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/tutorial/CodingExercise/C/2-mistake \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/tutorial/CodingExercise/C/1-skeleton \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/test \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/contrib/LinearSolverLoader \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/contrib/LinearSolverLoader/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/contrib/CGPenalty \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/contrib/CGPenalty/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/LinAlg/TMatrices \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/LinAlg/TMatrices/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/LinAlg \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/LinAlg/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Interfaces \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Interfaces/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Common \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Common/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Apps/CUTErInterface \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Apps/CUTErInterface/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Algorithm/LinearSolvers \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Algorithm/LinearSolvers/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Algorithm \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/src/Algorithm/.libs \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/examples/hs071_c \
lib/scip/lib/shared/ipopt.linux.x86_64.gnu.opt/Ipopt/MSVisualStudio/v8-ifort/IpOptFSS \
lib/scip/lib/include/zimplinc/zimpl \
lib/scip/lib/include/zimplinc/zimpl/WIN \
lib/scip/lib/include/bliss \
lib/scip/interfaces/matlab \
lib/scip/interfaces/gams/src \
lib/scip/interfaces/ampl/src \
lib/scip/examples \
lib/scip/examples/VRP/doc \
lib/scip/examples/TSP/obj/O.linux.x86_64.gnu.dbg \
lib/scip/examples/TSP/doc \
lib/scip/examples/Relaxator/src \
lib/scip/examples/Relaxator/obj/static/O.linux.x86_64.gnu.dbg \
lib/scip/examples/Relaxator/obj/O.linux.x86_64.gnu.dbg \
lib/scip/examples/Relaxator/doc \
lib/scip/examples/MIPSolver/doc \
lib/scip/examples/LOP/src \
lib/scip/examples/LOP/doc \
lib/scip/examples/GMI/src \
lib/scip/examples/GMI/doc \
lib/scip/examples/Eventhdlr/src \
lib/scip/examples/Eventhdlr/doc \
lib/scip/examples/CallableLibrary/src \
lib/scip/examples/CallableLibrary/doc \
lib/scip/examples/Binpacking/src \
lib/scip/examples/Binpacking/doc \
lib/scip/doc \
lib/scip/applications/Scheduler/src \
lib/scip/applications/Scheduler/doc \
lib/scip/applications/STP/src \
lib/scip/applications/STP/doc \
lib/scip/applications/MinIISC/src \
lib/scip/applications/MinIISC/doc \
lib/scip/applications/CycleClustering/src \
lib/scip/applications/CycleClustering/doc \
lib/scip/applications/Coloring/src \
lib/scip/applications/Coloring/obj/static/O.linux.x86_64.gnu.dbg \
lib/scip/applications/Coloring/doc \
lib/scip/.git/refs/remotes/origin \
lib/scip/.git/logs/refs/remotes/origin \

