<p>
SCIP-SDP is developed in <a href="http://www.sfb805.tu-darmstadt.de/sfb805/m_bereiche/m_bereich_a/m_a4/index.en.jsp">subproject A4</a> of the <a href="http://www.sfb805.tu-darmstadt.de/sfb805/m_forschungsziel/c_forschungsziel_3.en.jsp">
Collaborative Research Centre 805 – Control of Uncertainty in Load-Carrying Structures in Mechanical Engineering</a> funded by the <a href="http://www.dfg.de/en/index.jsp">
German Research Foundation</a>.
</p>
<div class="row">
   <div class="col-sm-4 col-xs-6" div style="margin-top:-5px;">
            <a target="_blank" href="http://www.sfb805.tu-darmstadt.de/sfb805/m_forschungsziel/c_forschungsziel_3.en.jsp"><img src="http://www.sfb805.tu-darmstadt.de/media/sfb805/f_bilder/f_layout/Logo_SFB.png" width="150" height="70" alt="SFB 805"></a>
   </div>
   <div class="col-sm-4 col-xs-6">
            <a target="_blank" href="http://www.dfg.de/en/index.jsp"><img src="http://dfg.de/zentralablage/bilder/service/bildarchiv/dfg_schriftzug/dfg_logo_schriftzug_blau_458_75.jpg"  width="458" height="75" alt="DFG"></a>
   </div>
</div>
