<p style="margin-bottom:1cm;">
SCIP-SDP has been developed in <a href="https://www.sfb805.tu-darmstadt.de/m_forschung/m_bereiche/m_bereich_a/m_a4/index.en.jsp">Subproject A4</a> of the <a href="https://www.sfb805.tu-darmstadt.de">
Collaborative Research Centre 805 – Control of Uncertainty in Load-Carrying Structures in Mechanical Engineering</a>
and in the <a href="https://www.projekt-express.tu-darmstadt.de">EXPRESS project</a> within the priority program 1798 <a href="https://www.mathc.rwth-aachen.de/spp1798ii/">CoSIP</a>, both funded by the <a href="http://www.dfg.de/en/index.jsp">German Research Foundation</a>.
</p>
