<p style="margin-bottom:1cm;">
SCIP-SDP is developed in <a href="http://www.sfb805.tu-darmstadt.de/sfb805/m_bereiche/m_bereich_a/m_a4/index.en.jsp">subproject A4</a> of the <a href="http://www.sfb805.tu-darmstadt.de/sfb805/m_forschungsziel/c_forschungsziel_3.en.jsp">
Collaborative Research Centre 805 – Control of Uncertainty in Load-Carrying Structures in Mechanical Engineering</a>
and in the <a href="https://www.projekt-express.tu-darmstadt.de/dfg_projekt_express/dfg_projekt_express_1.en.jsp">EXPRESS project</a> within the priority program 1798 <a href="https://www.mathc.rwth-aachen.de/spp1798ii/">CoSIP</a>, both funded by the <a href="http://www.dfg.de/en/index.jsp">German Research Foundation</a>.
</p>
<div class="row">
   <div class="col-sm-4 col-xs-6" div style="margin-top:-5px;">
            <a target="_blank" href="http://www.sfb805.tu-darmstadt.de/sfb805/m_forschungsziel/c_forschungsziel_3.en.jsp"><img src="http://www.sfb805.tu-darmstadt.de/media/sfb805/f_bilder/f_layout/Logo_SFB.png" width="150" height="70" alt="SFB 805"></a>
   </div>
   <div class="col-sm-4 col-xs-6">
            <a target="_blank" href="http://www.dfg.de/en/index.jsp"><img src="http://www.opt.tu-darmstadt.de/scipsdp/dfg_logo_schriftzug_blau.jpg"  height="70" alt="DFG"></a>
   </div>
</div>
