<h3>Main developers</h3>
<table class="desc">
   <tr>
      <td><a href="http://www3.mathematik.tu-darmstadt.de/index.php?id=2575">Tristan Gally</a>
      </td>
   </tr>
   <tr>
      <td>
      <a href="http://www.mathematik.tu-darmstadt.de/~pfetsch/">Marc Pfetsch</a>
      </td>
   </tr>
</table>
<h3>Former main developers</h3>
<table class="desc">
   <tr>
      <td><a href="http://www3.mathematik.tu-darmstadt.de/index.php?id=675">Sonja Mars</a>
      </td>
   </tr>
   <tr>
      <td>
      <a href="http://www.mso.math.uni-erlangen.de/edom/team/schewe-lars/dr-lars-schewe.html">Lars Schewe</a>
      </td>
   </tr>
</table>
<h3>Contributors</h3>
<table class="desc">
   <tr>
      <td><a href="http://www.zib.de/members/gleixner">Ambros Gleixner</a>
      </td>
   </tr>
   <tr>
      <td>
      <a href="http://www.mso.math.fau.de/edom/team/schelbert-jakob/jakob-schelbert/">Jakob Schelbert</a>
      </td>
   </tr>
</table>
