<h3>Main developers</h3>
<table class="desc">
   <tr>
      <td>
      <a href="https://www.mathematik.tu-darmstadt.de/optimierung/arbeitsgruppe_optimierung/personen_1/personendetails/index.en.jsp">Frederic Matter</a>
      </td>
   </tr>
   <tr>
      <td>
      <a href="http://www.mathematik.tu-darmstadt.de/~pfetsch/">Marc Pfetsch</a>
      </td>
   </tr>
</table>
<h3>Former main developers</h3>
<table class="desc">
   <tr>
      <td>Tristan Gally&nbsp;&nbsp;&nbsp;</td>
      <td>(main development from version 2.0.0 to 3.1.1)</td>
   </tr>
   <tr>
      <td>Sonja Mars</td>
      <td>(original program creator, version 1.0)</td>
   </tr>
   <tr>
      <td>Lars Schewe</td>
      <td>(support for version 1.0)</td>
   </tr>
</table>
<h3>Contributors</h3>
<table class="desc">
   <tr>
      <td>Henrik Alsing Friberg</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/members/gleixner">Ambros Gleixner</a>
      </td>
   </tr>
   <tr>
      <td>Jakob Schelbert</td>
   </tr>
</table>
