<p>
The files you can download here come without any warranty. Use at your own risk! Please refer to the provided <a href="http://www.opt.tu-darmstadt.de/scipsdp/downloads/INSTALL">INSTALL</a> file for help on installing the software.
</p><br>
<p>You can download the source code here:</p>
<ul>
<li><a href="http://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-4.2.0.tgz">scipsdp-4.2.0.tgz</a></li>
</ul>
<p>Old versions from the following list can also be downloaded: </p>
<ul>
<li><a href="https://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-4.1.0.tgz">scipsdp-4.1.0.tgz</a></li>
<li><a href="https://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-4.0.0.tgz">scipsdp-4.0.0.tgz</a></li>
<li><a href="https://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-3.2.0.tgz">scipsdp-3.2.0.tgz</a></li>
<li><a href="https://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-3.1.2.tgz">scipsdp-3.1.2.tgz</a></li>
<li><a href="https://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-3.1.1.tgz">scipsdp-3.1.1.tgz</a></li>
<li><a href="https://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-3.1.0.tgz">scipsdp-3.1.0.tgz</a></li>
<li><a href="https://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-3.0.1.tgz">scipsdp-3.0.1.tgz</a></li>
<li><a href="https://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-3.0.0.tgz">scipsdp-3.0.0.tgz</a></li>
<li><a href="https://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-2.1.0.tgz">scipsdp-2.1.0.tgz</a></li>
<li><a href="https://www.opt.tu-darmstadt.de/scipsdp/downloads/scipsdp-2.0.0.tgz">scipsdp-2.0.0.tgz</a></li>
<li><a href="https://wwwopt.mathematik.tu-darmstadt.de/scipsdp/SCIPSDP1/SCIP_SDP.zip">scipsdp-1.0.zip</a></li>
</ul>
