<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
     <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse"> <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button> <a href="http://scip.zib.de/#scipoptsuite" class="navbar-brand">SCIP Optimization Suite</a>
     </div>
     <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown"> <a href="http://www.opt.tu-darmstadt.de/scipsdp/doc/html" class="dropdown-toggle" data-toggle="dropdown">Documentation <b class="caret"></b></a>
               <ul class="dropdown-menu">
                    <!--choose right folder for both versions-->
                    <li><a href="http://www.opt.tu-darmstadt.de/scipsdp/doc-3.1.2/html">SCIP-SDP 3.1.2</a></li>
                    <li><a href="http://www.opt.tu-darmstadt.de/scipsdp/doc-3.1.1/html">SCIP-SDP 3.1.1</a></li>
                    <li><a href="http://www.opt.tu-darmstadt.de/scipsdp/doc-3.1.0/html">SCIP-SDP 3.1.0</a></li>
                    <li><a href="http://www.opt.tu-darmstadt.de/scipsdp/doc-3.0.1/html">SCIP-SDP 3.0.1</a></li>
                    <li><a href="http://www.opt.tu-darmstadt.de/scipsdp/doc-3.0.0/html">SCIP-SDP 3.0.0</a></li>
		    <li><a href="http://www.opt.tu-darmstadt.de/scipsdp/doc-2.1.0/html">SCIP-SDP 2.1.0</a></li>
                    <li><a href="http://www.opt.tu-darmstadt.de/scipsdp/doc-2.0.0/html">SCIP-SDP 2.0.0</a></li>
               </ul>
            </li>
        </ul>
     </nav>
  </div>
</header>
