<p>
This program is licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a>.
</p>

<table style="width:80%">
<tr><td>Copyright (C)</td><td> 2011-2013</td><td width="70%"> Discrete Optimization, TU Darmstadt   </td> </tr>
<tr><td></td><td></td><td>                         EDOM, FAU Erlangen-N&uuml;rnberg   </td></tr>
<tr><td></td><td>             2014-2024</td><td> Discrete Optimization, TU Darmstadt </td></tr>
</table>
<br>
<p>It is based on <a href="scipopt.org">SCIP - Solving Constraint Integer Programs</a>, Copyright (C) 2002-2024 Zuse Institute Berlin.</p>
