<p>
This program is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version. </p>

<table style="width:80%">
<tr><td>Copyright (C)</td><td> 2011-2013</td><td width="70%"> Discrete Optimization, TU Darmstadt   </td> </tr>          
<tr><td></td><td></td><td>                         EDOM, FAU Erlangen-N&uuml;rnberg   </td></tr>                   
<tr><td></td><td>             2014-2015</td><td> Discrete Optimization, TU Darmstadt </td></tr>          
</table>
<br><br>
<p>It is based on SCIP - Solving Constraint Integer Programs. SCIP is distributed under the terms of the SCIP Academic Licence, see file COPYING in the SCIP distribution.  </p>

<table style="width:80%">
  <tr><td>Copyright (C)</td><td> 2002-2015</td><td width="70%"> Zuse Institute Berlin </td></tr>
</table>
<br><br>
<p>
   <b>Any publication for which SCIP-SDP is used should include an acknowledgment and a reference to the following article:</b>
<ul>
   <li><a href="http://www.optimization-online.org/DB_HTML/2016/04/5394.html">A Framework for Solving Mixed-Integer Semidefinite Programs</a> <br> <i> Tristan Gally, Marc E. Pfetsch, and Stefan Ulbrich </i> <br>  Technical report, Optimization-Online, 2016</li>
</ul>
   An <a href="http://www.opt.tu-darmstadt.de/scipsdp/downloads/OnlineSupplement-GallyPfetschUlbrich-FrameworkMISDP.pdf">online supplement with detailed results</a> and the <a href="http://www.opt.tu-darmstadt.de/scipsdp/downloads/FrameworkMISDP-instances.tar.gz">corresponding instances</a> are also available.
</p>
