<p>
This program is licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a>.
</p>

<table style="width:80%">
<tr><td>Copyright (C)</td><td> 2011-2013</td><td width="70%"> Discrete Optimization, TU Darmstadt   </td> </tr>
<tr><td></td><td></td><td>                         EDOM, FAU Erlangen-N&uuml;rnberg   </td></tr>
<tr><td></td><td>             2014-2024</td><td> Discrete Optimization, TU Darmstadt </td></tr>
</table>
<br><br>
<p>It is based on <a href="scipopt.org">SCIP - Solving Constraint Integer Programs</a>, Copyright (C) 2002-2024 Zuse Institute Berlin.</p>
<br><br>
<p>
   <b>Any publication using SCIP-SDP should include an acknowledgment and a reference to the following article:</b>
<ul>
   <li><a href="http://dx.doi.org/10.1080/10556788.2017.1322081">A Framework for Solving Mixed-Integer Semidefinite Programs</a> <br> <i> Tristan Gally, Marc E. Pfetsch, and Stefan Ulbrich </i> <br>  Optimization Methods and Software, 33(3):594-632, 2018. <a href="http://dx.doi.org/10.1080/10556788.2017.1322081">DOI: 10.1080/10556788.2017.1322081</a></li>
</ul>
   A <a href="http://www.optimization-online.org/DB_HTML/2016/04/5394.html">preprint</a>, an <a href="http://www.opt.tu-darmstadt.de/scipsdp/downloads/OnlineSupplement-GallyPfetschUlbrich-FrameworkMISDP.pdf">online supplement with detailed results</a> and the corresponding instances (<a href="http://www.opt.tu-darmstadt.de/scipsdp/downloads/FrameworkMISDP-instances-CBF.tar.gz">CBF</a> / <a href="http://www.opt.tu-darmstadt.de/scipsdp/downloads/FrameworkMISDP-instances.tar.gz">SDPA</a>-format) are also available.
</p>
