<p>
  The following articles cover many ideas implemented in SCIP-SDP:
</p>
<ul>
  <li>
    <a href="http://dx.doi.org/10.1080/10556788.2017.1322081">A Framework for Solving Mixed-Integer Semidefinite Programs</a> <br>
    <i> Tristan Gally, Marc E. Pfetsch, and Stefan Ulbrich </i> <br>
    Optimization Methods and Software, 33(3):594-632, 2018.<br>
    <a href="http://dx.doi.org/10.1080/10556788.2017.1322081">DOI: 10.1080/10556788.2017.1322081</a>,
    Preprint: <a href="http://www.optimization-online.org/DB_HTML/2016/04/5394.html">Optimization Online</a><br>
    An <a href="http://www.opt.tu-darmstadt.de/scipsdp/downloads/OnlineSupplement-GallyPfetschUlbrich-FrameworkMISDP.pdf">online supplement with detailed results</a> and the corresponding instances (<a href="http://www.opt.tu-darmstadt.de/scipsdp/downloads/FrameworkMISDP-instances-CBF.tar.gz">CBF</a> / <a href="http://www.opt.tu-darmstadt.de/scipsdp/downloads/FrameworkMISDP-instances.tar.gz">SDPA</a>-format) are also available.
  </li>
  <li>
    <a href="https://doi.org/10.1287/ijoo.2022.0079">Presolving for Mixed-Integer Semidefinite Optimization</a><br>
    <i>Frederic Matter and Marc E. Pfetsch</i><br>
    INFORMS Journal on Optimization 5, No. 2, 131-154 (2022)<br>
    <a href="https://doi.org/10.1287/ijoo.2022.0079">DOI:10.1287/ijoo.2022.0079</a>,
    Preprint: <a href="http://www.optimization-online.org/DB_HTML/2021/10/8614.html">Optimization Online</a><br>
    <a href="https://www2.mathematik.tu-darmstadt.de/~pfetsch/MISDP-presolving.html">Detailed results and problem data</a>.
  </li>
  <li>
    <a href="https://doi.org/10.1007/978-3-031-33271-5_5">Handling Symmetries in Mixed-Integer Semidefinite Programs</a><br>
    <i>Christopher Hojny, Marc E. Pfetsch</i>
    Proc. of CPAIOR 2023, 69-78<br>
    <a href="https://doi.org/10.1007/978-3-031-33271-5_5">DOI:10.1007/978-3-031-33271-5_5</a>,
    Preprint: <a href="https://optimization-online.org/2022/12/handling-symmetries-in-mixed-integer-semidefinite-programs/">Optimization Online</a>.
  </li>
</ul>
