<table class="desc">
   <tr>
      <td class="w-120 val-t" width="30%">Decemberr 2022</td>
      <td>SCIP-SDP 4.1.0 is released for SCIP 8.0.2 and DSDP 5.8 or SDPA 7.3.8 or MOSEK 9.x or 10.x
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">October 2021</td>
      <td>New paper "Presolving for Mixed-Integer Semidefinite Optimization": <a href="https://www2.mathematik.tu-darmstadt.de/~pfetsch/MISDP-presolving.html">paper and data</a>.
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">September 2021</td>
      <td>SCIP-SDP 4.0.0 is released for SCIP 8.0.0 and DSDP 5.8 or SDPA 7.3.8 or MOSEK 9.x
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">March 2020</td>
      <td>SCIP-SDP 3.2.0 is released for SCIP 7.0.0 and DSDP 5.8 or SDPA 7.3.8 or MOSEK 9.x
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">June 2019</td>
      <td>SCIP-SDP 3.1.2 is released for SCIP 6.0.2 and DSDP 5.8 or SDPA 7.3.8 or MOSEK 9.x
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">June 2018</td>
      <td>SCIP-SDP 3.1.1 is released for SCIP 6.0.0 and DSDP 5.8 or SDPA 7.3.8 or MOSEK 8.1.x
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">December 2017</td>
      <td>SCIP-SDP 3.1.0 is released for SCIP 5.0.0 and DSDP 5.8 or SDPA 7.3.8 or MOSEK 8.1.x
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">September 2017</td>
      <td>SCIP-SDP 3.0.1 is released for SCIP 4.0.1 and DSDP 5.8 or SDPA 7.3.8 or MOSEK 8.1.x
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">March 2017</td>
      <td>SCIP-SDP 3.0.0 is released for SCIP 4.0.0 and DSDP 5.8 or SDPA 7.3.8 or MOSEK 8.0.0.x
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">May 2016</td>
      <td>SCIP-SDP 2.1.0 is released for SCIP 3.2.1 and DSDP 5.8 or SDPA 7.3.8
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">June 2015</td>
      <td>SCIP-SDP 2.0.0 is released for SCIP 3.2.0 and DSDP 5.8 or SDPA 7.3.8
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t">July 2012</td>
      <td><a href="http://www.opt.tu-darmstadt.de/~smars/scip_sdp.html">SCIP-SDP 1.0</a> is released for SCIP 3.0.0 and DSDP 5.8</td>
   </tr>
</table><br><br>
