<table class="desc">
   <tr>
      <td class="w-120 val-t" width="30%">September 2017</td>
      <td>SCIP-SDP 3.0.1 is released for SCIP 4.0.1 and DSDP 5.8 or SDPA 7.3.8 or MOSEK 8.1.x
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">March 2017</td>
      <td>SCIP-SDP 3.0.0 is released for SCIP 4.0.0 and DSDP 5.8 or SDPA 7.3.8 or MOSEK 8.0.0.x
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">May 2016</td>
      <td>SCIP-SDP 2.1.0 is released for SCIP 3.2.1 and DSDP 5.8 or SDPA 7.3.8
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t" width="30%">June 2015</td>
      <td>SCIP-SDP 2.0.0 is released for SCIP 3.2.0 and DSDP 5.8 or SDPA 7.3.8
      </td>
   </tr>
   <tr>
      <td class="w-120 val-t">July 2012</td>
      <td><a href="http://www.opt.tu-darmstadt.de/~smars/scip_sdp.html">SCIP-SDP 1.0</a> is released for SCIP 3.0.0 and DSDP 5.8</td>
   </tr>
</table><br><br>
