<div class="bs-sidebar hidden-print" role="complementary">
   <ul class="nav bs-sidenav">
      <li><a href="#about">About</a></li>
      <li><a href="#news">News</a></li>
      <li><a href="#literature">Literature</a></li>
      <li><a href="#license">License</a></li>
      <li><a href="#bugs">Bugs</a></li>
      <li><a href="#developers">Developers</a></li>
      <li><a href="#download">Download</a></li>
      <li><a href="#cooperation">Cooperation</a></li>
   </ul>
</div>

