SCIP-SDP: prop_sdpredcost.c File Reference
prop_sdpredcost.c File Reference
reduced cost fixing for SDPs
Macros
Propagator properties
#define PROP_NAME "sdpredcost"
#define PROP_DESC "sdp reduced cost strengthening propagator"
#define PROP_TIMING (SCIP_PROPTIMING_DURINGLPLOOP | SCIP_PROPTIMING_AFTERLPLOOP)
#define PROP_PRIORITY +1000000
#define PROP_FREQ 1
#define PROP_DELAY FALSE
Functions
static SCIP_RETCODE sdpRedcostFixingBinary (SCIP *scip, SCIP_VAR *var, SCIP_Real primallbval, SCIP_Real primalubval, SCIP_Real cutoffbound, SCIP_Real relaxval, SCIP_RESULT *result)
static SCIP_DECL_PROPEXEC (propExecSdpredcost)
static SCIP_DECL_PROPFREE (propFreeSdpredcost)
static SCIP_DECL_PROPINITSOL (propInitsolSdpredcost)
static SCIP_DECL_PROPCOPY (propCopySdpredcost)
SCIP_RETCODE SCIPincludePropSdpredcost (SCIP *scip)
Detailed Description
reduced cost fixing for SDPs
Author
Tristan Gally
Definition in file prop_sdpredcost.c.
Macro Definition Documentation
#define PROP_NAME "sdpredcost"
Definition at line 50 of file prop_sdpredcost.c.
Referenced by SCIP_DECL_PROPCOPY(), and SCIPincludePropSdpredcost().
#define PROP_DESC "sdp reduced cost strengthening propagator"
Definition at line 51 of file prop_sdpredcost.c.
Referenced by SCIPincludePropSdpredcost().
#define PROP_TIMING (SCIP_PROPTIMING_DURINGLPLOOP | SCIP_PROPTIMING_AFTERLPLOOP)
Definition at line 52 of file prop_sdpredcost.c.
Referenced by SCIPincludePropSdpredcost().
#define PROP_PRIORITY +1000000
propagator priority
Definition at line 53 of file prop_sdpredcost.c.
Referenced by SCIPincludePropSdpredcost().
#define PROP_FREQ 1
propagator frequency
Definition at line 54 of file prop_sdpredcost.c.
Referenced by SCIPincludePropSdpredcost().
#define PROP_DELAY FALSE
should propagation method be delayed, if other propagators found reductions?
Definition at line 55 of file prop_sdpredcost.c.
Referenced by SCIPincludePropSdpredcost().
Function Documentation
static SCIP_RETCODE sdpRedcostFixingBinary (SCIP * scip, SCIP_VAR * var, SCIP_Real primallbval, SCIP_Real primalubval, SCIP_Real cutoffbound, SCIP_Real relaxval, SCIP_RESULT * result) static
reduced cost fixing for binary variables
If the corresponding primal variable for the lower bound is bigger than the cutoff bound minus the current relaxation value, then the variable can be fixed to zero, if the primal variable for the upper bound is bigger than this value, then it can be fixed to one.
Parameters
scip pointer to SCIP data structure
var variable to propagate
primallbval value of the primal variable corresponding to the lower bound
primalubval value of the primal variable corresponding to the upper bound
cutoffbound current cutoffbound in SCIP
relaxval optimal objective value of the current relaxation
result pointer to return result
Definition at line 75 of file prop_sdpredcost.c.
Referenced by SCIP_DECL_PROPEXEC().
static SCIP_DECL_PROPEXEC (propExecSdpredcost) static
reduced cost propagation method
Definition at line 132 of file prop_sdpredcost.c.
References SCIPrelaxSdpGetPrimalBoundVars(), SCIPrelaxSdpGetSdpNode(), SCIPrelaxSdpRelaxVal(), SCIPrelaxSdpSolvedOrig(), and sdpRedcostFixingBinary().
static SCIP_DECL_PROPFREE (propFreeSdpredcost) static
free the propagator data
Definition at line 217 of file prop_sdpredcost.c.
static SCIP_DECL_PROPINITSOL (propInitsolSdpredcost) static
allocate memory for the primal variable values
Definition at line 239 of file prop_sdpredcost.c.
static SCIP_DECL_PROPCOPY (propCopySdpredcost) static
copy method for propagator plugins (called when SCIP copies plugins)
Definition at line 257 of file prop_sdpredcost.c.
References PROP_NAME, and SCIPincludePropSdpredcost().
SCIP_RETCODE SCIPincludePropSdpredcost (SCIP * scip)
creates the Sdpredcost propagator and includes it in SCIP
Parameters
scip SCIP data structure
Definition at line 270 of file prop_sdpredcost.c.
References PROP_DELAY, PROP_DESC, PROP_FREQ, PROP_NAME, PROP_PRIORITY, and PROP_TIMING.
Referenced by runSCIP(), and SCIP_DECL_PROPCOPY().