SCIP-SDP: SdpVarmapper.h File Reference
SdpVarmapper.h File Reference
class that maps SCIP variables to SDP indices (the SCIP variables are given SDP indices in the order in which they were inserted)
Typedefs
typedef struct Sdpvarmapper SdpVarmapper
Functions
EXTERN SCIP_RETCODE SCIPsdpVarmapperCreate (SCIP *scip, SdpVarmapper **varmapper, int size)
EXTERN SCIP_RETCODE SCIPsdpVarmapperFree (SCIP *scip, SdpVarmapper **varmapper)
EXTERN SCIP_RETCODE SCIPsdpVarmapperAddVars (SCIP *scip, SdpVarmapper *varmapper, int nvars, SCIP_VAR **vars)
EXTERN SCIP_RETCODE SCIPsdpVarmapperInsertVar (SCIP *scip, SdpVarmapper *varmapper, SCIP_VAR *var, int pos)
EXTERN int SCIPsdpVarmapperGetNVars (SdpVarmapper *varmapper)
EXTERN SCIP_Bool SCIPsdpVarmapperExistsSCIPvar (SdpVarmapper *varmapper, SCIP_VAR *var)
EXTERN int SCIPsdpVarmapperGetSdpIndex (SdpVarmapper *varmapper, SCIP_VAR *var)
EXTERN SCIP_VAR * SCIPsdpVarmapperGetSCIPvar (SdpVarmapper *varmapper, int ind)
EXTERN SCIP_RETCODE SCIPsdpVarmapperRemoveSdpIndex (SCIP *scip, SdpVarmapper *varmapper, int ind)
EXTERN SCIP_RETCODE SCIPsdpVarmapperTransform (SCIP *scip, SdpVarmapper *varmapper)
EXTERN SCIP_RETCODE SCIPsdpVarmapperClone (SCIP *scip, SdpVarmapper *oldmapper, SdpVarmapper *newmapper)
Detailed Description
class that maps SCIP variables to SDP indices (the SCIP variables are given SDP indices in the order in which they were inserted)
Author
Tristan Gally
Definition in file SdpVarmapper.h.
Typedef Documentation
typedef struct Sdpvarmapper SdpVarmapper
Definition at line 48 of file SdpVarmapper.h.
Function Documentation
EXTERN SCIP_RETCODE SCIPsdpVarmapperCreate (SCIP * scip, SdpVarmapper ** varmapper, int size)
creates the SDP Varmapper
Parameters
scip SCIP data structure
varmapper Pointer to the Varmapper that should be created
size initial size of the sciptosdp-hashmap
Definition at line 55 of file SdpVarmapper.c.
Referenced by SCIP_DECL_RELAXINIT().
EXTERN SCIP_RETCODE SCIPsdpVarmapperFree (SCIP * scip, SdpVarmapper ** varmapper)
frees the SDP Varmapper
Parameters
scip SCIP data structure
varmapper Pointer to the Varmapper that should be freed
Definition at line 80 of file SdpVarmapper.c.
Referenced by SCIP_DECL_RELAXEXIT().
EXTERN SCIP_RETCODE SCIPsdpVarmapperAddVars (SCIP * scip, SdpVarmapper * varmapper, int nvars, SCIP_VAR ** vars)
adds the given variables (if not already existent) to the end of the Varmapper
Parameters
scip SCIP data structure
varmapper Varmapper to add variables to
nvars number of variables to add to the varmapper
vars SCIP variables to add to the varmapper
Definition at line 106 of file SdpVarmapper.c.
Referenced by SCIP_DECL_RELAXINIT(), and SCIPsdpVarmapperInsertVar().
EXTERN SCIP_RETCODE SCIPsdpVarmapperInsertVar (SCIP * scip, SdpVarmapper * varmapper, SCIP_VAR * var, int pos)
adds the given variable (if not already existant) to the Varmapper at the given position
adds the given variable (if not already existent) to the Varmapper at the given position
Parameters
scip SCIP data structure
varmapper Varmapper to add variables to
var SCIP variable to add to the varmapper
pos position where the variable should be added
Definition at line 156 of file SdpVarmapper.c.
References SCIPsdpVarmapperAddVars().
EXTERN int SCIPsdpVarmapperGetNVars (SdpVarmapper * varmapper)
gets the number of variables
Parameters
varmapper Varmapper to get number of variables for
Definition at line 200 of file SdpVarmapper.c.
EXTERN SCIP_Bool SCIPsdpVarmapperExistsSCIPvar (SdpVarmapper * varmapper, SCIP_VAR * var)
Is the given SCIP variable included in the varmapper?
Parameters
varmapper Varmapper to get variable index for
var SCIP variables to get sdp index for
Definition at line 210 of file SdpVarmapper.c.
EXTERN int SCIPsdpVarmapperGetSdpIndex (SdpVarmapper * varmapper, SCIP_VAR * var)
gets the sdp index for the given SCIP variable
Parameters
varmapper Varmapper to get variable index for
var SCIP variables to get sdp index for
Definition at line 222 of file SdpVarmapper.c.
Referenced by putLpDataInInterface(), and putSdpDataInInterface().
EXTERN SCIP_VAR* SCIPsdpVarmapperGetSCIPvar (SdpVarmapper * varmapper, int ind)
gets the corresponding SCIP variable for the given sdp variable index
Parameters
varmapper Varmapper to get variable index for
ind index of the sdp variable
Definition at line 234 of file SdpVarmapper.c.
Referenced by calc_relax().
EXTERN SCIP_RETCODE SCIPsdpVarmapperRemoveSdpIndex (SCIP * scip, SdpVarmapper * varmapper, int ind)
removes the variable for the given Sdp index from the varmapper, decreasing the indices of all later variables by 1
Parameters
scip SCIP data structure
varmapper Varmapper to get variable index for
ind index of the sdp variable
Definition at line 246 of file SdpVarmapper.c.
EXTERN SCIP_RETCODE SCIPsdpVarmapperTransform (SCIP * scip, SdpVarmapper * varmapper)
swaps all SCIP variables for their transformed counterparts
Parameters
scip SCIP data structure
varmapper pointer to the Varmapper that should be transformed
Definition at line 281 of file SdpVarmapper.c.
EXTERN SCIP_RETCODE SCIPsdpVarmapperClone (SCIP * scip, SdpVarmapper * oldmapper, SdpVarmapper * newmapper)
clones the varmapper in the second argument to the varmapper in the third argument
Parameters
scip SCIP data structure
oldmapper pointer to the Varmapper that should be cloned
newmapper pointer to the Varmapper that should become a clone of the other one
Definition at line 309 of file SdpVarmapper.c.